export const DataItems = {
  Telangana: [
  { img: "https://cdn.s3waas.gov.in/s3072b030ba126b2f4b2374f342be9ed44/uploads/bfi_thumb/2018062119-olw6fy7l5uwgroojon82fbjmdfbssfi3mm6rieimsg.jpg", title: "Adilabad" },
  { img: "https://chaloghumane.com/wp-content/uploads/2021/09/Bhadradri-Kothagudem.jpg", title: "Bhadradri Kothagudem" },
  { img: "https://c7.alamy.com/zooms/9/2fa310614a934ea594dc0e9b51caf0d2/ac6nx7.jpg", title: "Hanumakonda" },
  { img: "https://wallpapercave.com/wp/wp10257499.jpg", title: "Hyderabad" },
  { img: "https://4.bp.blogspot.com/-lRnaLJUmAE4/UjHECVh7hkI/AAAAAAAABIs/2Ap51vD8cAk/s1600/Clock_tower_in_jagtial.jpg", title: "Jagtial" },
  { img: "https://media.telanganatoday.com/wp-content/uploads/2022/10/Jagoan.jpg", title: "Jangaon" },
  { img: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgip3ZCr6ZYChq3noAi8bYM3ve9ilFSmg2SqkzNgWGyhkiB5TYA1Ur3J0yeZ3t43rbyirc58zC7k0QuyunGJZaPtxZjN8Z1T29A7BAcROpCbee8BNXcZ4Wdmkf7VxgdfbHyS-Z6G8dZzLckVWrSvTUrxNWgiesXd3CYbFrOzXuu3z1Mc1w1gWX5acMTwA/w400-h225/Kotagullu in Jayashankar Bhupalpally.jpg", title: "Jayashankar Bhupalapally" },
  { img: "https://www.bing.com/th/id/OIP.I2m6T0j1N-6xqK9Z_cGrGgHaE8?w=285&h=211&c=8&rs=1&qlt=90&o=6&cb=thwsc4&dpr=1.3&pid=3.1&rm=2", title: "Jogulamba Gadwal" },
  { img: "https://www.bing.com/th/id/OIP.-WL89Qg_Tp4Kwn1pGanx9wHaEc?w=247&h=211&c=8&rs=1&qlt=90&o=6&cb=thwsc4&dpr=1.3&pid=3.1&rm=2", title: "Kamareddy" },
  { img: "https://www.bing.com/th/id/OIP.P8QWs-T12I8jav7n-z1OdQHaE6?w=269&h=211&c=8&rs=1&qlt=90&o=6&cb=thwsc4&dpr=1.3&pid=3.1&rm=2", title: "Karimnagar" },
  { img: "https://www.bing.com/th/id/OIP.qkh46pgygffFuJmIbFytGgHaE8?w=250&h=211&c=8&rs=1&qlt=90&o=6&cb=thwsc4&dpr=1.3&pid=3.1&rm=2", title: "Khammam" },
  { img: "https://www.bing.com/th/id/OIP.Msa3WlmRlBUGpLSNYZFA3gAAAA?w=258&h=211&c=8&rs=1&qlt=90&o=6&cb=thwsc4&dpr=1.3&pid=3.1&rm=2", title: "Kumuram Bheem Asifabad" },
  { img: "<map or Unsplash photo>", title: "Mahabubabad" },
  { img: "<map or Unsplash photo>", title: "Mahbubnagar" },
  { img: "<map or Unsplash photo>", title: "Mancherial" },
  { img: "<map or Unsplash photo>", title: "Medak" },
  { img: "<map or Unsplash photo>", title: "Medchal‑Malkajgiri" },
  { img: "<map or Unsplash photo>", title: "Mulugu" },
  { img: "<map or Unsplash photo>", title: "Nagarkurnool" },
  { img: "<map or Unsplash photo>", title: "Nalgonda" },
  { img: "<map or Unsplash photo>", title: "Narayanpet" },
  { img: "<map or Unsplash photo>", title: "Nirmal" },
  { img: "<map or Unsplash photo>", title: "Nizamabad" },
  { img: "<map or Unsplash photo>", title: "Peddapalli" },
  { img: "<map or Unsplash photo>", title: "Rajanna Sircilla" },
  { img: "<map or Unsplash photo>", title: "Ranga Reddy" },
  { img: "<map or Unsplash photo>", title: "Sangareddy" },
  { img: "<map or Unsplash photo>", title: "Siddipet" },
  { img: "<map or Unsplash photo>", title: "Suryapet" },
  { img: "<map or Unsplash photo>", title: "Vikarabad" },
  { img: "<map or Unsplash photo>", title: "Wanaparthy" },
  { img: "<map or Unsplash photo>", title: "Warangal" },
  { img: "<map or Unsplash photo>", title: "Yadadri Bhuvanagiri" }
]

,

    AndhraPradesh: [
  { img: "https://thedanceindia.com/wp-content/uploads/2020/11/Annamayya.jpg", title: "Annamayya" },
  { img: "https://chaloghumane.com/wp-content/uploads/2021/08/Anantapur-1400x800.jpg", title: "Anantapur" },
  { img: "https://media-cdn.tripadvisor.com/media/photo-s/06/47/7c/d6/surya-lanka-beach.jpg", title: "Bapatla" },
  { img: "https://www.holidify.com/images/bgImages/CHITTOOR.jpg", title: "Chittoor" },
  { img: "https://www.indianholiday.com/pictures/travelguide/other-images/dest_head_img-396.jpeg", title: "Eluru" },
  { img: "https://www.shutterstock.com/image-photo/aerial-view-rural-road-passing-600nw-2263696159.jpg", title: "Guntur" },
  { img: "https://i.ytimg.com/vi/8xtDfsgWxFI/maxresdefault.jpg", title: "Kakinada" },
  { img: "https://i.pinimg.com/originals/02/ae/74/02ae74b5ac0a32f60c3bf0d871831f8a.jpg", title: "Konaseema" },
  { img: "https://divinecartravels.in/wp-content/uploads/2021/08/krishna-district.jpg", title: "Krishna" },
  { img: "https://cimages1.touristlink.com/repository/K/U/R/N/O/O/L/F/kurnool-fort_1.jpg", title: "Kurnool" },
  { img: "https://www.adequatetravel.com/Images/Ek%20Mukhi%20Datta%20Temple%20-%20Narsobawadi%20In%20Maharashtra.png", title: "Manyam" },
  { img: "https://tse2.mm.bing.net/th/id/OIP.FmrCpxkjALRaA9yyedsB6AHaFj?r=0&rs=1&pid=ImgDetMain&o=7&rm=3", title: "Nandyal" },
  { img: "https://source.unsplash.com/featured/?temple", title: "Nellore" },
  { img: "https://source.unsplash.com/featured/?river", title: "NTR" },
  { img: "https://source.unsplash.com/featured/?palnadu", title: "Palnadu" },
  { img: "https://source.unsplash.com/featured/?beach", title: "Parvathipuram Manyam" },
  { img: "https://source.unsplash.com/featured/?hillstation", title: "Prakasam" },
  { img: "https://source.unsplash.com/featured/?port", title: "Srikakulam" },
  { img: "https://source.unsplash.com/featured/?tirumala", title: "Sri Balaji" },
  { img: "https://source.unsplash.com/featured/?temple", title: "Sri Satya Sai" },
  { img: "https://source.unsplash.com/featured/?statue", title: "Tirupati" },
  { img: "https://source.unsplash.com/featured/?bridge", title: "Visakhapatnam" },
  { img: "https://source.unsplash.com/featured/?harbor", title: "Vizianagaram" },
  { img: "https://source.unsplash.com/featured/?nature", title: "West Godavari" },
  { img: "https://source.unsplash.com/featured/?waterfalls", title: "YSR Kadapa" }
],
ArunachalPradesh:[
  {img:"https://travelogyindia.b-cdn.net/storage/app/upload/tawang-monastery-1.jpg",title:"Tawang"},
  {img:"https://www.adotrip.com/public/images/city/5c3daabec00fb-West%20Kameng%20district%20Trip.jpg",title:"West Kameng"},
  {img:"https://tse3.mm.bing.net/th/id/OIP.eyYCTG_XN4BoGdKY_5jjnwHaEO?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",title:"Bichom "},
  {img:"https://chaloghumane.com/wp-content/uploads/2021/08/East-Kameng.jpg",title:"East Kameng	"},
  {img:"https://i.ytimg.com/vi/En9yVF0hwus/hqdefault.jpg",title:"Pakke-Kessang	"},
  {img:"https://chaloghumane.com/wp-content/uploads/2021/08/Kurung-Kumey.jpg",title:"Kurung Kumey	"},
  {img:"https://images.wanderon.in/blogs/new/2024/04/park-in-pampu-pare-district.jpg",title:"Papum Pare	"},
  {img:"https://www.adotrip.com/public/images/city/5c3da9f3047fd-Itanagar%20Package%20Tour.jpg",title:"Itanagar"},
  {img:"https://chaloghumane.com/wp-content/uploads/2021/08/Kra-Daadi-768x473.jpg",title:"Kra Daadi	"},
  {img:"https://diprarunachal.org/wp-content/uploads/2024/11/lowsub.jpg",title:"Lower Subansiri	"},
  {img:"https://chaloghumane.com/wp-content/uploads/2021/08/Kamle-tour-arunachal.jpg",title:"Kamle"},
  {img:"https://tse3.mm.bing.net/th/id/OIP.TS46RZ_9kSraeqplPO1scwHaEK?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",title:"Keyi Panyor (New)"},
  {img:"https://media-cdn.tripadvisor.com/media/photo-c/1280x250/05/1f/f1/26/daporijo-island.jpg",title:"Upper Subansiri	"},
  {img:"https://tse1.mm.bing.net/th/id/OIP.zlHJ84FbBE_uAJKYGyNM5wHaEK?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",title:"Shi Yomi	"},
  {img:"https://tse2.mm.bing.net/th/id/OIP.mhTm8nTsEPJrGY8kBTbbGAAAAA?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",title:"West Siang	"},
  {img:"https://tse4.mm.bing.net/th/id/OIP.lxkeweiaX8MYQmSBPeaX4AHaE5?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",title:"Siang	"},
  {img:"",title:""},
  {img:"",title:""},
  {img:"",title:""},
  {img:"",title:""},
  {img:"",title:""},
  {img:"",title:""},
  {img:"",title:""},
  {img:"",title:""},
  {img:"",title:""},
  {img:"",title:""},
  {img:"",title:""},
  {img:"",title:""}


],
Assam:[
  {img:"https://www.adotrip.com/public/images/city/5f44f1dfd1c95-Baksa%20Trip.jpg",title:"Baksa"},
  {img:"https://chaloghumane.com/wp-content/uploads/2021/08/Barpeta.jpg",title:"Barpeta"},
  {img:"https://tse1.mm.bing.net/th/id/OIP.fvLhQeCijY-18jMXvyyoYgHaEg?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",title:"Biswanath"},
  {img:"https://tse3.mm.bing.net/th/id/OIP.eARlM0VePBpbl8BwLSEZywHaFj?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",title:"Bongaigaon"},
  {img:"https://chaloghumane.com/wp-content/uploads/2021/08/Cachar-1400x800.jpg",title:"Cachar"},
  {img:"https://assets.zeezest.com/blogs/PROD_Charaideo%20Maidam%20(1)_1722944526098_thumb_1200.jpeg?w=1200&q=75",title:"Charaideo"},
  {img:"https://tse1.mm.bing.net/th/id/OIP.oaK8l23R8n0c5cd0qOUGWQHaFR?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",title:""},
  {img:"https://th.bing.com/th/id/R.f55672dff6418128e37611f7461cdea3?rik=Rh%2buAcgISMjgsw&riu=http%3a%2f%2fwww.onefivenine.com%2fimages%2fdistrictimages%2fAssam%2fDarrang%2f2.jpg&ehk=Bq61ggLeOo05kYm5g6fF0cQnWK9VWH%2bEdtt2IAHxCCw%3d&risl=&pid=ImgRaw&r=0",title:"Darrang"},
  {img:"https://www.hlimg.com/images/places2see/738X538/h_1536576010m.jpg",title:"Dhemaji"},
  {img:"https://th.bing.com/th/id/R.cafbc5f2a4407cac183599307f878871?rik=EqlV8gU11YNPkQ&riu=http%3a%2f%2fdiscoversikhism.com%2fimages%2fgurdwara%2fgurdwara_sri_damdama_sahib_dhubri%2fgurdwara_sri_damdama_sahib_dhubri7.jpg&ehk=hRCGlN0i%2bj9XkewHibdNHcd8Z%2bVpvifsCURZqf33Yl0%3d&risl=&pid=ImgRaw&r=0",title:"Dhubri"},
  {img:"https://tse2.mm.bing.net/th/id/OIP.SxF-FbkYERvQxNR_bIWRIgHaC6?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",title:"Dibrugarh"},
  {img:"https://www.shutterstock.com/image-photo/maibang-maibong-valley-dima-hasao-600nw-1919718407.jpg",title:"Dima Hasao (autonomous)"},
  {img:"https://d368ufu7xgcs86.cloudfront.net/22537-1578386302.jpg",title:"Goalpara"},
  {img:"https://peopleplaces.in/wp-content/uploads/2022/11/Negheriting-Shiva-Doul.jpg",title:"Golaghat"},
  {img:"https://i.ytimg.com/vi/c2IAFcNEpjc/maxresdefault.jpg",title:"Hailakandi"},
  {img:"https://i.ytimg.com/vi/0Bh__rKpTew/maxresdefault.jpg",title:"Hojai"}
  

]

}
